export { default as 맹구 } from "./child/맹구.png"
export { default as 유리 } from "./child/유리.png"
export { default as 수지 } from "./child/수지.png"
export { default as 짱구 } from "./child/짱구.png"
export { default as 철수 } from "./child/철수.png"
export { default as 훈이 } from "./child/훈이.png"
